relativeURLs = true
title = "Jonathan Old"
theme = ["academimal"]
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" , "make.sh"]

[params]
    shortbio = "Predoc at LSE. Interested in political economy and development economics."
    logo = "wald.jpg" 
    

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  