relativeURLs = true
title = "Jonathan Old"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Predoc at the LSE, future Economics PhD student"
    logo = "wald.jpg" 
    
