relativeURLs = true
title = "Jonathan Old"
theme = ["academimal"]
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" , "make.sh"]

[params]
    shortbio = "Predoc at the LSE, future Economics PhD student"
    ORCID = "0000-0003-3256-4700"
    officeAddress = "32-G918"
    logo = "wald.jpg" 
    

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  